/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGenerateClothingRouteImport } from './routes/api/generate-clothing'
import { Route as ApiCatalogSearchRouteImport } from './routes/api/catalog-search'
import { Route as ApiCatalogItemRouteImport } from './routes/api/catalog-item'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateClothingRoute = ApiGenerateClothingRouteImport.update({
  id: '/api/generate-clothing',
  path: '/api/generate-clothing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalogSearchRoute = ApiCatalogSearchRouteImport.update({
  id: '/api/catalog-search',
  path: '/api/catalog-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalogItemRoute = ApiCatalogItemRouteImport.update({
  id: '/api/catalog-item',
  path: '/api/catalog-item',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/catalog-item': typeof ApiCatalogItemRoute
  '/api/catalog-search': typeof ApiCatalogSearchRoute
  '/api/generate-clothing': typeof ApiGenerateClothingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/catalog-item': typeof ApiCatalogItemRoute
  '/api/catalog-search': typeof ApiCatalogSearchRoute
  '/api/generate-clothing': typeof ApiGenerateClothingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/catalog-item': typeof ApiCatalogItemRoute
  '/api/catalog-search': typeof ApiCatalogSearchRoute
  '/api/generate-clothing': typeof ApiGenerateClothingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/catalog-item'
    | '/api/catalog-search'
    | '/api/generate-clothing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/catalog-item'
    | '/api/catalog-search'
    | '/api/generate-clothing'
  id:
    | '__root__'
    | '/'
    | '/api/catalog-item'
    | '/api/catalog-search'
    | '/api/generate-clothing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCatalogItemRoute: typeof ApiCatalogItemRoute
  ApiCatalogSearchRoute: typeof ApiCatalogSearchRoute
  ApiGenerateClothingRoute: typeof ApiGenerateClothingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-clothing': {
      id: '/api/generate-clothing'
      path: '/api/generate-clothing'
      fullPath: '/api/generate-clothing'
      preLoaderRoute: typeof ApiGenerateClothingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalog-search': {
      id: '/api/catalog-search'
      path: '/api/catalog-search'
      fullPath: '/api/catalog-search'
      preLoaderRoute: typeof ApiCatalogSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalog-item': {
      id: '/api/catalog-item'
      path: '/api/catalog-item'
      fullPath: '/api/catalog-item'
      preLoaderRoute: typeof ApiCatalogItemRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCatalogItemRoute: ApiCatalogItemRoute,
  ApiCatalogSearchRoute: ApiCatalogSearchRoute,
  ApiGenerateClothingRoute: ApiGenerateClothingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
